# Generated by Django 2.1.2 on 2019-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balls', '0003_result_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='level',
            field=models.IntegerField(),
        ),
    ]
