# Generated by Django 2.1.2 on 2019-02-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balls', '0005_ballsredballs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BallsRedBalls',
        ),
    ]
