# Generated by Django 2.1.2 on 2019-02-17 15:55

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('balls', '0006_delete_ballsredballs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='red_balls',
        ),
        migrations.AddField(
            model_name='result',
            name='clicked_balls',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='target_balls',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
