# Generated by Django 2.1.2 on 2019-02-10 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reaction_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result_1',
            new_name='ReactionTestResult',
        ),
        migrations.AlterModelOptions(
            name='reactiontestresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Result'},
        ),
    ]
