# Generated by Django 2.1.2 on 2019-02-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction_test', '0003_reactiontestresult_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactiontestresult',
            name='mode',
            field=models.CharField(max_length=20),
        ),
    ]
