# Generated by Django 2.1.2 on 2019-03-03 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardMouseCoordinationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.CharField(max_length=20)),
                ('time', models.FloatField()),
                ('hit', models.CharField(max_length=20)),
                ('speed', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('keyboard_step', models.IntegerField()),
                ('sensitivity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
