# Generated by Django 2.1.2 on 2019-03-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_mouse_coordination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyboardmousecoordinationresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Result'},
        ),
    ]
